name: Debug R Environment

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - name: Set Up R
      uses: r-lib/actions/setup-r@v2

    - name: Debug R Library Paths
      run: |
        echo "R version:"
        Rscript -e "R.version.string"
        echo "R Library Paths:"
        Rscript -e ".libPaths()"

    - name: Debug Environment Variables
      run: |
        echo "Environment Variables:"
        printenv
