name: Update Map and Timestamp

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual runs

jobs:
  update-map:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Install System Dependencies
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev

    # Step 3: Set Up R
    - name: Set Up R
      uses: r-lib/actions/setup-r@v2

    # Step 4: Install R Packages
    - name: Install R Packages
      run: |
        Rscript -e "install.packages('sf', dependencies = TRUE)"
        Rscript -e "install.packages('terra', dependencies = TRUE)"
        Rscript -e "install.packages('raster', dependencies = TRUE)"
        Rscript -e "install.packages(c('dplyr', 'dotenv', 'leaflet', 'htmlwidgets', 'ggplot2', 'lubridate', 'here'))"

    # Step 5: Run the R Script
    - name: Run R Script
      env:
        PURPLEAIR_API_KEY: ${{ secrets.PURPLEAIR_API_KEY }}
      run: Rscript purpleair_map.R

    # Step 6: Commit and Push Changes
    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add maps/
        git commit -m "Automated update of map and timestamp"
        git push
